import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';

const pack = JSON.parse(fs.readFileSync('little_wandle_master_voice_pack_v3.json', 'utf8'));
assert.equal(pack.clips.length, 75, 'All 75 teacher clips must be published.');
assert.equal(new Set(pack.clips.map(clip => clip.id)).size, 75, 'Clip ids must be unique.');
assert.ok(pack.clips.every(clip => clip.base64Audio.startsWith('data:audio/wav;base64,')), 'Every clip must be playable WAV audio.');
assert.ok(pack.clips.find(clip => clip.id === 'ed-d'), 'The supplied -ed /d/ clip must be included.');

const wordPack = JSON.parse(fs.readFileSync('little_wandle_word_voice_pack.json', 'utf8'));
assert.ok(Array.isArray(wordPack.clips), 'The publishable teacher word voice pack must have a clips array.');
assert.equal(wordPack.clips.length, 93, 'All 93 teacher-recorded tricky words must be published.');
assert.equal(new Set(wordPack.clips.map(clip => clip.id)).size, 93, 'Tricky-word recording IDs must be unique.');
assert.ok(wordPack.clips.every(clip => clip.base64Audio.startsWith('data:audio/wav;base64,')), 'Every tricky word must contain playable teacher WAV audio.');
assert.equal(pack.version, '6.0-deeper-voice-teacher-pack', 'The phonics pack must use the deeper teacher voice profile.');
assert.equal(wordPack.version, '2.0-deeper-voice-teacher-pack', 'The tricky-word pack must use the deeper teacher voice profile.');
assert.equal(pack.voiceProfile?.pitchSemitones, -3.44, 'The phonics voice profile must preserve the approved pitch shift.');
assert.equal(wordPack.voiceProfile?.pitchSemitones, -3.44, 'Both packs must use the same teacher voice profile.');

const app = fs.readFileSync('index.html', 'utf8');
const worker = fs.readFileSync('cloudflare/worker.mjs', 'utf8');
assert.match(app, /<div class="brand-title">Visual Dictionary<\/div>/, 'The pupil header must use the Visual Dictionary identity.');
assert.match(app, /assets\/visual-dictionary-logo\.png/, 'The original Visual Dictionary logo must be published with the pupil app.');
assert.match(app, /Definitions, examples and pronunciations from[\s\S]*Merriam-Webster's Elementary Dictionary[\s\S]*Whole-word and read-aloud voice by[\s\S]*ElevenLabs[\s\S]*Merriam-Webster audio is used when the voice service is unavailable/, 'Content and audio providers must be credited accurately.');
const bundleMatch = app.match(/const AUDIO_BUNDLE = (.*?);\s*const AUDIO_CACHE/s);
assert.ok(bundleMatch, 'The pupil app must contain its published audio bundle.');
const embedded = JSON.parse(bundleMatch[1]);
assert.deepEqual(embedded.clips, pack.clips, 'Teacher Studio and pupil app must use identical audio.');
const wordBundleMatch = app.match(/const WORD_AUDIO_BUNDLE = (.*?);\s*const WORD_AUDIO_CACHE/s);
assert.ok(wordBundleMatch, 'The standalone pupil app must embed the teacher tricky-word recordings.');
const embeddedWords = JSON.parse(wordBundleMatch[1]);
assert.deepEqual(embeddedWords.clips, wordPack.clips, 'The standalone app and published tricky-word pack must use identical recordings.');
assert.match(app, /function isAcceptedDictionaryEntry[\s\S]*?entry\.meta[\s\S]*?entry\.ins[\s\S]*?entry\.hwi/, 'Dictionary results must be filtered by provider-owned accepted forms.');
assert.match(app, /const shortDefinitions[\s\S]*?shortDefinitions\.length/, 'Elementary short definitions must be preferred over raw technical sense text.');
assert.match(app, /function applyDictionaryPronunciation/, 'Selected dictionary pronunciations must control ambiguous phonics.');
assert.match(app, /function buildVerifiedImageQueries/, 'Image searches must be built from the selected verified sense.');
assert.match(app, /conflictingAudioUrls/, 'Provider audio shared by different pronunciations must be blocked.');
assert.match(app, /wordAudioFor\(pronunciationRecordingId/, 'Exact teacher pronunciation recordings must override provider audio.');
assert.match(app, /const API_PROXY_BASE = 'https:\/\/prep2-phonics-api\.goldenhappyaku\.workers\.dev'/, 'The pupil app must use the deployed Cloudflare API proxy.');
assert.doesNotMatch(app, /MERRIAM_WEBSTER_API_KEY|ELEVENLABS_API_KEY|xi-api-key|api\/v3\/references\/sd2|api\.elevenlabs\.io/, 'Provider keys and direct provider endpoints must not ship to pupils.');
assert.match(worker, /env\.MERRIAM_WEBSTER_API_KEY[\s\S]*env\.ELEVENLABS_API_KEY/, 'Cloudflare must read both provider keys from encrypted Worker secrets.');
assert.match(worker, /Xb7hH8MSUJpSbSDYk0k2|env\.ELEVENLABS_VOICE_ID/, 'The Worker must use the configured British voice.');
assert.match(worker, /eleven_multilingual_v2[\s\S]*stability: 0\.85[\s\S]*speed: 0\.82/, 'The Worker must own the high-clarity speech settings.');
assert.match(app, /function playElevenLabsSpeech[\s\S]*fetch\(ELEVENLABS_ENDPOINT[\s\S]*JSON\.stringify\(\{ text: normalizedSpeechText \}\)/, 'Read-aloud must request speech through Cloudflare without a browser key.');
assert.match(app, /function speakNaturalWord[\s\S]*playElevenLabsSpeech[\s\S]*onFailure: \(\) => playAudioUrl/, 'Whole-word audio must try ElevenLabs and preserve the exact dictionary fallback.');
assert.match(app, /const SOUND_MODE_PIN = '8888'/, 'Teacher voice unlock must use the requested PIN.');
assert.match(app, /let isSilentMode = true/, 'The pupil app must start in silent mode.');
assert.match(app, /function playSound[\s\S]*if \(isSilentMode\)[\s\S]*setTimeout\(clearHighlight/, 'Silent sound buttons must keep their visual feedback without playing audio.');
assert.match(app, /id="soundAttemptPanel" hidden[\s\S]*id="soundAnswerPanel"/, 'Silent searches must include one inline Try It First activity before the completed answer.');
assert.match(app, /function renderSoundButtons[\s\S]*isSilentMode[\s\S]*completedSoundChallenges[\s\S]*renderSoundChallengePanel/, 'Silent searches must withhold completed sound buttons until the child succeeds.');
assert.match(app, /Tap one letter for one sound[\s\S]*straight line through every letter[\s\S]*Curve around letters[\s\S]*split sound/, 'The challenge must teach tap, straight-team, and curved split-sound gestures clearly.');
assert.match(app, /class="sound-builder-gesture-path"[\s\S]*function collectSoundLettersAlongSegment[\s\S]*state\.dragVisitedIndices/, 'A visible gesture path must track and highlight each letter crossed during a drag.');
assert.match(app, /\.sound-attempt-panel\.focused[\s\S]*position: fixed;[\s\S]*backdrop-filter: blur\(12px\)[\s\S]*\.sound-attempt-sheet/, 'Silent practice must open in a focused, blurred-backdrop workspace.');
assert.match(app, /\.sound-builder-split-svg[^}]*overflow: hidden[\s\S]*\.sound-builder-gesture-svg[^}]*overflow: hidden/, 'Gesture and split-link drawings must stay clipped to the practice board.');
assert.match(app, /const visibleLeft = board\.scrollLeft[\s\S]*Math\.max\(visibleLeft, Math\.min\(visibleRight, rawX\)\)[\s\S]*Math\.max\(0, Math\.min\(board\.clientHeight, rawY\)\)/, 'Captured pointer paths must be clamped to the visible practice board.');
assert.match(app, /function minimiseSoundChallengeWorkspace[\s\S]*activeSoundChallenge\.minimized = true[\s\S]*function openSoundChallengeWorkspace[\s\S]*activeSoundChallenge\.minimized = false/, 'Children must be able to return to the word and reopen the same unfinished attempt.');
assert.match(app, /maximum - minimum > 1 && !everyCrossedLetterSelected[\s\S]*\[start, end\]/, 'A curved gesture must be able to propose any skipped-letter split so children can make and inspect mistakes.');
assert.match(app, /This curved link skips letters[\s\S]*This straight line joins more than one sound[\s\S]*work together as one sound/, 'Feedback must use reliable structural categories for split links, joined sounds, and divided letter teams.');
assert.match(app, /state\.attempts = Math\.min\(3/, 'Unsuccessful checks must stop at the third-attempt teacher-support state.');
assert.match(app, /state\.blocked = true[\s\S]*Call a teacher over to help you[\s\S]*attempt is now locked/, 'The third unsuccessful check must lock the attempt for teacher support without an automatic reveal.');
assert.match(app, /isBlocked \? 'disabled'[\s\S]*state\.blocked\) return/, 'A locked attempt must disable its visible controls and reject further edits.');
assert.match(app, /const VERIFIED_TRICKY_WORDS = \[[\s\S]*father[\s\S]*shoe[\s\S]*const MASTER_TRICKY_WORDS_SET/, 'The verified 93-word Little Wandle list must be embedded.');
const verifiedTrickyBlock = app.match(/const VERIFIED_TRICKY_WORDS = \[([\s\S]*?)\];\s*const MASTER_TRICKY_WORDS_SET/)[1];
const verifiedTrickyWords = [...verifiedTrickyBlock.matchAll(/\.\.\.\[(.*?)\]\.map\(word/gs)]
  .flatMap(match => [...match[1].matchAll(/'([^']+)'/g)].map(wordMatch => wordMatch[1]));
const teachingNotesSource = app.match(/const TRICKY_WORD_TEACHING_NOTES = (\[[\s\S]*?\])\.reduce/)[1];
const teachingNotes = vm.runInNewContext(teachingNotesSource);
assert.equal(verifiedTrickyWords.length, 93, 'The verified tricky-word inventory must stay at 93 words.');
assert.equal(teachingNotes.length, 93, 'Every verified tricky word must have ordered teaching guidance.');
assert.deepEqual(
  Array.from(teachingNotes, note => note.word.toLowerCase()).sort(),
  verifiedTrickyWords.map(word => word.toLowerCase()).sort(),
  'Ordered teaching guidance must cover exactly the verified tricky-word inventory.'
);
teachingNotes.forEach(note => {
  assert.equal(note.segments.map(segment => segment.replace(/^!/, '')).join('').toLowerCase(), note.word.toLowerCase(), `${note.word} segments must rebuild the printed word in order.`);
  assert.ok(note.segments.some(segment => segment.startsWith('!')), `${note.word} must identify at least one tricky part.`);
  assert.ok(note.tip && note.tip.length > 8, `${note.word} must explain the sound contrast clearly.`);
});
assert.deepEqual(Array.from(teachingNotes.find(note => note.word === 'water').segments), ['w', '!a', 't', 'er'], 'Water must show w-a-t-er in order with only a marked tricky.');
assert.match(app, /Read each card from left to right[\s\S]*Green[\s\S]*Red and underlined/, 'The tricky-word page must explain the colour system once, clearly.');
assert.match(app, /tw\.segments\.map[\s\S]*segment\.startsWith\('!'\)[\s\S]*tricky-part-separator/, 'Every card must render its ordered green and red segments from the verified model.');
assert.match(app, /isSilentMode \? 'Read it yourself first'/, 'Silent tricky-word cards must prompt independent reading instead of replacing guidance with a mode label.');
const trickyAudioFunction = app.match(/async function playTrickyWordAudio[\s\S]*?\n    }/)[0];
assert.match(trickyAudioFunction, /wordAudioFor\(trickyRecordingId\(word\)\)/, 'Tricky words must use the matching teacher recording.');
assert.doesNotMatch(trickyAudioFunction, /ElevenLabs|resolveDictionaryWord|dictionaryAudio/, 'Tricky words must never fall back to AI or dictionary voice.');
assert.match(app, /id="resContextPhrase" hidden/, 'Image-search context must stay off the dictionary page.');
assert.match(app, /function speakCurrentDefinition/, 'Definitions must expose read-aloud.');
assert.match(app, /Search “\$\{suggestion\.word\}”/, 'Every typed word must keep an exact-search action.');
assert.doesNotMatch(app, /Different Picture Idea|btnLevelEasy|btnLevelHard/, 'Misleading picture shuffling and duplicate puzzle levels must stay removed.');
assert.doesNotMatch(app, /currentWordAudioUrl|PRIMARY_CURATED_DB/, 'Audio and meanings must not come from stale global or offline dictionary state.');
assert.doesNotMatch(app, /I can see the word/, 'The pupil app must not fabricate a generic sentence when the provider has no example.');
assert.doesNotMatch(app, /setAndLookup\('farted'\)|"farmer","fart","farted","farting","fast"/, 'Suggestions must not advertise the unsupported fart word family.');
assert.match(app, /\.filter\(item => item\.senseIndex !== currentActiveSenseIdx\)/, 'The selected main meaning must not be repeated among alternative meanings.');
assert.match(app, /id="btnToggleMeanings"[\s\S]*?id="otherMeaningsPanel" hidden[\s\S]*?Not what you were looking for\? Try another meaning\./, 'Alternative meanings must use a calm, progressively disclosed help box.');
assert.match(app, /function findVerifiedWordFormContext[\s\S]*?if \(!requestedContext\) return null;[\s\S]*?grammar\.inflections[\s\S]*?grammar\.stems/, 'Only explicit Time Machine navigation may open a verified word-form lesson.');
assert.match(app, /function openWordFamilyForm[\s\S]*?form\.word[\s\S]*?baseWord[\s\S]*?setAndLookup\(baseWord, model\.job\)/, 'A base word must return to a normal search instead of becoming another form of itself.');
assert.match(app, /id="wordFamilyDetails" hidden[\s\S]*?id="grammarRuleBadge" hidden/, 'The Time Machine and its rule information must begin collapsed.');
assert.match(app, /word: forms\.past, note: notes\.past[\s\S]*?word: forms\.ing, note: notes\.ing/, 'Regular spelling guidance must be attached to the relevant form rather than the whole family.');
assert.match(app, /\.sound-buttons-container \{ padding: 18px 12px; min-width: 0; \}/, 'The real sound-button container must receive mobile spacing.');
assert.match(app, /\.sound-buttons-row \{[\s\S]*?width: max-content;[\s\S]*?align-self: flex-start;/, 'Long phoneme rows must start at the reachable edge of their mobile scroll area.');
const decorativeEmoji = /[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u;
assert.doesNotMatch(app, decorativeEmoji, 'The pupil interface must not contain decorative emoji.');
const studio = fs.readFileSync('studio.html', 'utf8');
assert.match(studio, /const TRICKY_WORD_RECORDINGS = \[[^\]]+\]/, 'The studio must expose tricky-word recording targets.');
const trickyRecordingList = studio.match(/const TRICKY_WORD_RECORDINGS = \[([\s\S]*?)\];/)[1];
assert.equal((trickyRecordingList.match(/'[^']+'/g) || []).length, 93, 'Teacher Studio must expose all 93 verified tricky words for recording.');
assert.match(studio, /function exportWordVoicePack/, 'The studio must export a publishable word voice pack.');
assert.match(studio, /phonics_recording_review:[\s\S]*function recordingNeedsReview[\s\S]*function setRecordingReviewFlag/, 'Teacher review flags must persist locally for sounds and words.');
assert.match(studio, /reviewCheckboxMarkup\('sound'[\s\S]*reviewCheckboxMarkup\('word'/, 'Every sound and word recording card must expose a Needs review checkbox beneath its status.');
assert.match(studio, /function openRecordingBooth\(filterMode = 'review'\)[\s\S]*recordingNeedsReview\('sound'[\s\S]*recordingNeedsReview\('word'/, 'The default rapid booth must contain only teacher-flagged sounds and words.');
assert.match(studio, /filterMode === 'tricky'[\s\S]*target\.kind === 'Tricky word'/, 'Teacher Studio must provide a rapid tricky-word recording queue.');
assert.match(studio, /processAndSaveBlob\(sound\.id, audioBlob, sound\.targetType\)/, 'The rapid booth must save both sound and whole-word recordings through the correct storage path.');
assert.match(studio, /same browser[\s\S]*no extra sync step is needed[\s\S]*Export Sound Pack[\s\S]*Export Word Voice Pack[\s\S]*send the downloaded JSON file/, 'The studio must explain automatic local use versus publishing for every pupil.');
assert.doesNotMatch(studio, /Use on This Browser|syncAllToStudentApp/, 'The studio must not present a timestamp write as a manual sync operation.');
assert.match(studio, /\.sound-actions-row \{[\s\S]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/, 'Studio sound actions must use a non-clipping two-column grid.');
assert.match(studio, /<span>Download WAV<\/span>/, 'The WAV download control must have a clear label.');
assert.doesNotMatch(studio, decorativeEmoji, 'Teacher Studio must not contain decorative emoji.');
assert.equal(studio, fs.readFileSync('studio/index.html', 'utf8'), 'Both Teacher Studio routes must remain identical.');
console.log('Content checks passed: calm primary meanings, default teacher-locked silent mode, 93 verified tricky words, safe audio, and publishable teacher recordings.');
