import assert from 'node:assert/strict';
import fs from 'node:fs';

const pack = JSON.parse(fs.readFileSync('little_wandle_master_voice_pack_v3.json', 'utf8'));
assert.equal(pack.clips.length, 75, 'All 75 teacher clips must be published.');
assert.equal(new Set(pack.clips.map(clip => clip.id)).size, 75, 'Clip ids must be unique.');
assert.ok(pack.clips.every(clip => clip.base64Audio.startsWith('data:audio/wav;base64,')), 'Every clip must be playable WAV audio.');
assert.ok(pack.clips.find(clip => clip.id === 'ed-d'), 'The supplied -ed /d/ clip must be included.');

const wordPack = JSON.parse(fs.readFileSync('little_wandle_word_voice_pack.json', 'utf8'));
assert.ok(Array.isArray(wordPack.clips), 'The publishable teacher word voice pack must have a clips array.');

const app = fs.readFileSync('index.html', 'utf8');
const bundleMatch = app.match(/const AUDIO_BUNDLE = (.*?);\s*const AUDIO_CACHE/s);
assert.ok(bundleMatch, 'The pupil app must contain its published audio bundle.');
const embedded = JSON.parse(bundleMatch[1]);
assert.deepEqual(embedded.clips, pack.clips, 'Teacher Studio and pupil app must use identical audio.');
assert.match(app, /function isAcceptedDictionaryEntry[\s\S]*?entry\.meta[\s\S]*?entry\.ins[\s\S]*?entry\.hwi/, 'Dictionary results must be filtered by provider-owned accepted forms.');
assert.match(app, /const shortDefinitions[\s\S]*?shortDefinitions\.length/, 'Elementary short definitions must be preferred over raw technical sense text.');
assert.match(app, /function applyDictionaryPronunciation/, 'Selected dictionary pronunciations must control ambiguous phonics.');
assert.match(app, /function buildVerifiedImageQueries/, 'Image searches must be built from the selected verified sense.');
assert.match(app, /conflictingAudioUrls/, 'Provider audio shared by different pronunciations must be blocked.');
assert.match(app, /wordAudioFor\(pronunciationRecordingId/, 'Exact teacher pronunciation recordings must override provider audio.');
assert.match(app, /const ELEVENLABS_API_KEY = 'sk_[^']+'/, 'A valid-format ElevenLabs key must be configured.');
assert.match(app, /Xb7hH8MSUJpSbSDYk0k2|JBFqnCBsd6RMkjVDRZzb/, 'The configured ElevenLabs voice must be a verified British voice.');
assert.match(app, /function playElevenLabsSpeech[\s\S]*eleven_multilingual_v2/, 'Read-aloud must use the high-clarity ElevenLabs speech path.');
assert.match(app, /function speakNaturalWord[\s\S]*playElevenLabsSpeech[\s\S]*onFailure: \(\) => playAudioUrl/, 'Whole-word audio must try ElevenLabs and preserve the exact dictionary fallback.');
assert.match(app, /function speakCurrentDefinition/, 'Definitions must expose read-aloud.');
assert.match(app, /Search “\$\{suggestion\.word\}”/, 'Every typed word must keep an exact-search action.');
assert.doesNotMatch(app, /Different Picture Idea|btnLevelEasy|btnLevelHard/, 'Misleading picture shuffling and duplicate puzzle levels must stay removed.');
assert.doesNotMatch(app, /currentWordAudioUrl|PRIMARY_CURATED_DB/, 'Audio and meanings must not come from stale global or offline dictionary state.');
assert.doesNotMatch(app, /I can see the word/, 'The pupil app must not fabricate a generic sentence when the provider has no example.');
assert.doesNotMatch(app, /setAndLookup\('farted'\)|"farmer","fart","farted","farting","fast"/, 'Suggestions must not advertise the unsupported fart word family.');
assert.match(app, /currentWordSenses\.forEach\(\(sense, senseIndex\)/, 'Every accepted dictionary meaning must receive its own selectable tab.');
assert.match(app, /\.sound-buttons-container \{ padding: 18px 12px; min-width: 0; \}/, 'The real sound-button container must receive mobile spacing.');
assert.match(app, /\.sound-buttons-row \{[\s\S]*?width: max-content;[\s\S]*?align-self: flex-start;/, 'Long phoneme rows must start at the reachable edge of their mobile scroll area.');
const decorativeEmoji = /[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u;
assert.doesNotMatch(app, decorativeEmoji, 'The pupil interface must not contain decorative emoji.');
const studio = fs.readFileSync('studio.html', 'utf8');
assert.match(studio, /s\.needsUpdate && \(!stem \|\| !stem\.hasAudio\)/, 'The studio must only flag clips that are actually missing.');
assert.match(studio, /const TRICKY_WORD_RECORDINGS = \[[^\]]+\]/, 'The studio must expose tricky-word recording targets.');
assert.match(studio, /function exportWordVoicePack/, 'The studio must export a publishable word voice pack.');
assert.match(studio, /this browser only[\s\S]*send that JSON file/, 'The studio must explain local-only use versus publishing for every pupil.');
assert.doesNotMatch(studio, decorativeEmoji, 'Teacher Studio must not contain decorative emoji.');
assert.equal(studio, fs.readFileSync('studio/index.html', 'utf8'), 'Both Teacher Studio routes must remain identical.');
console.log('Content checks passed: exact meanings, verified suggestions, emoji-free interfaces, mobile phoneme reachability, safe audio, and publishable teacher recordings.');
